/**
 *
 * @author Kjeld K. B. Massali <kjeldkarim@gmail.com>
 */

package Presentation;

import javax.swing.JFrame;

import DomainLogic.*;

public class MainGui extends JFrame {

    private FileHandlingLibrary fileDomainModel = null;
    private SocketHandlingLibrary socketDomainModel = null;

    private FileTree myMachineTree = null;
    private FileTree connectedMachineTree = null;

    /** Creates new form MainGui */
    public MainGui(FileHandlingLibrary fileDomainModel, SocketHandlingLibrary socketDomainModel) {
        this.fileDomainModel = fileDomainModel;
        this.socketDomainModel = socketDomainModel;
        initComponents();
        initTrees();
    }

    /**
     * Initializes a default value for the tree views
     */
    private void initTrees() {
        // My machine tree init code
        myMachineTree = new FileTree(fileDomainModel);
        myMachineScrollPane.add(myMachineTree);
        // Connected machine tree init code
        connectedMachineTree = new FileTree(fileDomainModel);
        connectedMachineScrollPane.add(connectedMachineTree);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        hostnameTextField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        moveToConnectedMachineButton = new javax.swing.JButton();
        moveToMyMachineButton = new javax.swing.JButton();
        myMachineScrollPane = new javax.swing.JScrollPane();
        connectedMachineScrollPane = new javax.swing.JScrollPane();
        toggleConnectedButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Machine: ");

        hostnameTextField.setText("<ip/hostname>");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setAutoscrolls(true);
        jSeparator1.setDoubleBuffered(true);

        jLabel2.setText("My machine:");

        jLabel3.setText("Connected machine:");

        moveToConnectedMachineButton.setText("----->");

        moveToMyMachineButton.setText("<-----");

        myMachineScrollPane.setDoubleBuffered(true);

        toggleConnectedButton.setText("Connect");
        toggleConnectedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleConnectedButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(76, 76, 76)
                        .add(moveToConnectedMachineButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(75, 75, 75)
                                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 58, Short.MAX_VALUE)
                                .add(moveToMyMachineButton))))
                    .add(layout.createSequentialGroup()
                        .add(103, 103, 103)
                        .add(jLabel1)
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(toggleConnectedButton)
                            .add(hostnameTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 216, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .add(95, 95, 95))
            .add(layout.createSequentialGroup()
                .add(67, 67, 67)
                .add(jLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 144, Short.MAX_VALUE)
                .add(jLabel3)
                .add(74, 74, 74))
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(myMachineScrollPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 223, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(connectedMachineScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(hostnameTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(toggleConnectedButton)
                .add(37, 37, 37)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabel2)
                    .add(jLabel3))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(connectedMachineScrollPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 265, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(moveToMyMachineButton)
                            .add(moveToConnectedMachineButton)))
                    .add(layout.createSequentialGroup()
                        .add(myMachineScrollPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 265, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Captures when the togglebutton is clicked. Performs a simple check to see
     * if we are connected or not.
     * @param evt ActionEvent... Eventhandler
     */
    private void toggleConnectedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleConnectedButtonActionPerformed
        if (socketDomainModel.isConnected()) {
            toggleConnectedButton.setText("Disconnect");
        }
        else {
            toggleConnectedButton.setText("Connect");
        }
        toggleConnectedButton.validate();
    }//GEN-LAST:event_toggleConnectedButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane connectedMachineScrollPane;
    private javax.swing.JTextField hostnameTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton moveToConnectedMachineButton;
    private javax.swing.JButton moveToMyMachineButton;
    private javax.swing.JScrollPane myMachineScrollPane;
    private javax.swing.JButton toggleConnectedButton;
    // End of variables declaration//GEN-END:variables

}
